site_name: BuilerPress
theme: material
extra_css:
    - css/extra.css

pages:
    - Introduction: index.md
    - Basic Setup: install.md
    - Theme Settings: customizer.md
    - Pages and Templates: create-pages.md
    - Adding Contents: add-contents.md
    - Visual Composer Elements: visual-composer.md
    - Shortcodes: shortcodes.md
    - How to: how-to.md

use_directory_urls: false


extra:
  palette:
    primary: 'indego'
    accent: 'deep orange'

markdown_extensions:
  - admonition
  - codehilite(guess_lang=false)
  - toc(permalink=true)