# Documentation for BuilderPress WordPress theme.
#
# Author: Inspiry Themes
# License: Copyright held by WPTie.
#
# MKDOCS http://www.mkdocs.org/
# mkdocs-material http://squidfunk.github.io/mkdocs-material/
site_name: BuilerPress
theme:
  name: 'material'
  palette:
    primary: 'amber'
    accent: 'amber'

extra_css:
    - css/extra.css


pages:
    - Introduction: index.md
    - Basic Setup: install.md
    - Theme Settings: customizer.md
    - Pages and Templates: create-pages.md
    - Adding Contents: add-contents.md
    - Visual Composer Elements: visual-composer.md
    - Shortcodes: shortcodes.md
    - How to: how-to.md

use_directory_urls: false



markdown_extensions:
  - admonition
  - codehilite(guess_lang=true,linenums=true)
  - toc(permalink=true)
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
     emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
  - meta

